### ISSUE TITLE
Could binding with "Array Field" in "Auto Form"?

### ISSUE THREAD

**Issue by thearabbit** [dalgard/meteor-viewmodel#12]
I use `array field` in `autoform` and then I would like to sum of amount

``` js
// Schema
Items = new SimpleSchema({
   item: .......
   $.qty: ........
   $.price:........
   $.amount:..........

   totalAmount:..........
});
<template>
   ..............
   {{> afQuickField name="amount"}}
   ..............

  {{> afQuickField name="totalAmount"}}
</template>
```

Please help me.

**Comment by dalgard** [comment]
You should start by removing `totalAmount` from your schema – the total amount should always be calculated by summing the items. If the items are in an array, this can be done with `reduce` (see example below).

Now `totalAmount` is not a field anymore, so you simply need a helper to output the sum. You can get the state of the array field reactively from AutoForm with `getFieldValue`.

If the template already has a `ViewModel` instance on it, you can declare the helper there. Otherwise, just use a regular Blaze helper. The function looks the same:

``` javascript
Template.myForm.helpers({  // or viewmodel
  totalAmount: function () {
    var items = AutoForm.getFieldValue("items");

    return _.reduce(items, function (total, item) {
      return total + item.amount;
    }, 0);
  }
});
```

``` html
{{> afQuickField name='items'}}

Total: {{totalAmount}}
```

**Comment by thearabbit** [comment]
Thanks for your reply, I will try soon.
But I don't understand how to use `bind` in

``` js
{{> afQickField ......... bin 'value: textName'}}
```

**Comment by dalgard** [comment]
You can not use `{{bind}}` this way, for a lot of reasons. You will see, when you become more experienced with Meteor.

Luckily, there's no real need for this use, because AutoForm is a viewmodel in itself.
